import { Injectable } from "@angular/core";


@Injectable({
    providedIn: 'root'
  })
export class CourseData{
    courses = [
        {
            id: 1,
            title: "Khóa học HTML & CSS cơ bản",
            subtitle: "Tạo nền tảng vững chắc",
            description: "Học HTML và CSS từ cơ bản đến nâng cao.",
            price: 0.00,
            duration: 20,
            language: "Tiếng Việt",
            level: "BEGINNER",
            thumbnail: "html-css-thumbnail.jpg",
            previewVideo: "html-css-preview.mp4",
            authorName: "Vũ Nguyễn Bá",
            authorAvatar: null,
            categoryName: "HTML & CSS",
            avgRating: 4.5,
            countRating: 120,
            status: "ACCEPTED"
        },
        {
            id: 2,
            title: "Khóa học JavaScript nâng cao",
            subtitle: "Thành thạo JavaScript",
            description: "Hiểu sâu về JavaScript và các kỹ thuật nâng cao.",
            price: 299.99,
            duration: 30,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "javascript-thumbnail.jpg",
            previewVideo: "javascript-preview.mp4",
            authorName: "Vũ Nguyễn Bá",
            authorAvatar: null,
            categoryName: "JavaScript",
            avgRating: 4.7,
            countRating: 95,
            status: "ACCEPTED"
        },
        {
            id: 3,
            title: "Lập trình Python từ cơ bản đến nâng cao",
            subtitle: "Chinh phục Python",
            description: "Khóa học Python dành cho người mới bắt đầu.",
            price: 199.99,
            duration: 25,
            language: "Tiếng Việt",
            level: "BEGINNER",
            thumbnail: "python-thumbnail.jpg",
            previewVideo: "python-preview.mp4",
            authorName: "Vũ Nguyễn Bá",
            authorAvatar: null,
            categoryName: "Python",
            avgRating: 4.6,
            countRating: 110,
            status: "ACCEPTED"
        },
        {
            id: 4,
            title: "Spring Boot nâng cao",
            subtitle: "Xây dựng ứng dụng thực tế",
            description: "Khóa học về Spring Boot dành cho lập trình viên chuyên nghiệp.",
            price: 399.99,
            duration: 35,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "spring-boot-thumbnail.jpg",
            previewVideo: "spring-boot-preview.mp4",
            authorName: "Vũ Nguyễn Bá",
            authorAvatar: null,
            categoryName: "Spring Boot",
            avgRating: 4.8,
            countRating: 80,
            status: "ACCEPTED"
        },
        {
            id: 5,
            title: "ReactJS từ cơ bản đến nâng cao",
            subtitle: "Làm chủ ReactJS",
            description: "Khóa học giúp bạn nắm vững ReactJS và xây dựng ứng dụng hiện đại.",
            price: 349.99,
            duration: 40,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "reactjs-thumbnail.jpg",
            previewVideo: "reactjs-preview.mp4",
            authorName: "Nguyễn Văn A",
            authorAvatar: null,
            categoryName: "ReactJS",
            avgRating: 4.7,
            countRating: 130,
            status: "ACCEPTED"
        },
        {
            id: 6,
            title: "Kubernetes & Docker",
            subtitle: "Triển khai ứng dụng chuyên nghiệp",
            description: "Tìm hiểu về Kubernetes và Docker để quản lý container hiệu quả.",
            price: 499.99,
            duration: 50,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "kubernetes-thumbnail.jpg",
            previewVideo: "kubernetes-preview.mp4",
            authorName: "Trần Thị B",
            authorAvatar: null,
            categoryName: "DevOps",
            avgRating: 4.9,
            countRating: 75,
            status: "ACCEPTED"
        },
        {
            id: 7,
            title: "Lập trình Flutter chuyên sâu",
            subtitle: "Xây dựng ứng dụng đa nền tảng",
            description: "Tạo ứng dụng iOS & Android với Flutter và Dart.",
            price: 399.99,
            duration: 45,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "flutter-thumbnail.jpg",
            previewVideo: "flutter-preview.mp4",
            authorName: "Lê Hoàng C",
            authorAvatar: null,
            categoryName: "Flutter",
            avgRating: 4.6,
            countRating: 90,
            status: "ACCEPTED"
        },
        {
            id: 8,
            title: "Machine Learning & AI",
            subtitle: "Ứng dụng AI vào thực tế",
            description: "Khóa học chuyên sâu về Machine Learning và AI.",
            price: 599.99,
            duration: 60,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "ml-ai-thumbnail.jpg",
            previewVideo: "ml-ai-preview.mp4",
            authorName: "Phạm Văn D",
            authorAvatar: null,
            categoryName: "AI & Machine Learning",
            avgRating: 4.8,
            countRating: 85,
            status: "ACCEPTED"
        },
        {
            id: 9,
            title: "Node.js & Express.js nâng cao",
            subtitle: "Xây dựng backend mạnh mẽ",
            description: "Học cách xây dựng API RESTful với Node.js và Express.js.",
            price: 299.99,
            duration: 30,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "nodejs-thumbnail.jpg",
            previewVideo: "nodejs-preview.mp4",
            authorName: "Nguyễn Hữu Tín",
            authorAvatar: null,
            categoryName: "Node.js",
            avgRating: 4.7,
            countRating: 120,
            status: "ACCEPTED"
        },
        {
            id: 10,
            title: "SQL & Database Management",
            subtitle: "Quản lý dữ liệu hiệu quả",
            description: "Hiểu rõ cách thiết kế, tối ưu hóa và quản lý cơ sở dữ liệu SQL.",
            price: 249.99,
            duration: 35,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "sql-thumbnail.jpg",
            previewVideo: "sql-preview.mp4",
            authorName: "Trần Minh Khoa",
            authorAvatar: null,
            categoryName: "Database",
            avgRating: 4.6,
            countRating: 105,
            status: "ACCEPTED"
        },
        {
            id: 11,
            title: "Golang cho lập trình viên",
            subtitle: "Lập trình hiệu suất cao",
            description: "Học Golang để xây dựng các ứng dụng hiệu suất cao và đa luồng.",
            price: 399.99,
            duration: 40,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "golang-thumbnail.jpg",
            previewVideo: "golang-preview.mp4",
            authorName: "Hoàng Đức Anh",
            authorAvatar: null,
            categoryName: "Golang",
            avgRating: 4.5,
            countRating: 85,
            status: "ACCEPTED"
        },
        {
            id: 12,
            title: "Lập trình C++ chuyên sâu",
            subtitle: "Chinh phục C++ từ A-Z",
            description: "Khóa học từ cơ bản đến nâng cao về C++.",
            price: 299.99,
            duration: 45,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "cpp-thumbnail.jpg",
            previewVideo: "cpp-preview.mp4",
            authorName: "Đặng Thanh Sơn",
            authorAvatar: null,
            categoryName: "C++",
            avgRating: 4.7,
            countRating: 95,
            status: "ACCEPTED"
        },
        {
            id: 13,
            title: "Blockchain & Smart Contracts",
            subtitle: "Bước vào thế giới Blockchain",
            description: "Tìm hiểu cách hoạt động của Blockchain và lập trình Smart Contracts.",
            price: 599.99,
            duration: 50,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "blockchain-thumbnail.jpg",
            previewVideo: "blockchain-preview.mp4",
            authorName: "Phạm Văn Lâm",
            authorAvatar: null,
            categoryName: "Blockchain",
            avgRating: 4.8,
            countRating: 80,
            status: "ACCEPTED"
        },
        {
            id: 14,
            title: "Django & Python Web Development",
            subtitle: "Xây dựng web với Django",
            description: "Học Django để phát triển các ứng dụng web mạnh mẽ bằng Python.",
            price: 349.99,
            duration: 35,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "django-thumbnail.jpg",
            previewVideo: "django-preview.mp4",
            authorName: "Ngô Văn Duy",
            authorAvatar: null,
            categoryName: "Python",
            avgRating: 4.7,
            countRating: 90,
            status: "ACCEPTED"
        },
        {
            id: 15,
            title: "Cybersecurity & Ethical Hacking",
            subtitle: "An toàn mạng & bảo mật",
            description: "Khóa học chuyên sâu về bảo mật mạng và hacking đạo đức.",
            price: 499.99,
            duration: 60,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "cybersecurity-thumbnail.jpg",
            previewVideo: "cybersecurity-preview.mp4",
            authorName: "Lê Thanh Hải",
            authorAvatar: null,
            categoryName: "Cybersecurity",
            avgRating: 4.9,
            countRating: 75,
            status: "ACCEPTED"
        },
        {
            id: 16,
            title: "Mobile App Development với Swift",
            subtitle: "Xây dựng ứng dụng iOS",
            description: "Khóa học lập trình iOS với Swift từ cơ bản đến nâng cao.",
            price: 399.99,
            duration: 50,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "swift-thumbnail.jpg",
            previewVideo: "swift-preview.mp4",
            authorName: "Nguyễn Văn Tiến",
            authorAvatar: null,
            categoryName: "Swift",
            avgRating: 4.6,
            countRating: 88,
            status: "ACCEPTED"
        },
        {
            id: 17,
            title: "Lập trình Game với Unity",
            subtitle: "Tạo game chuyên nghiệp",
            description: "Khóa học hướng dẫn lập trình game với Unity và C#.",
            price: 499.99,
            duration: 55,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "unity-thumbnail.jpg",
            previewVideo: "unity-preview.mp4",
            authorName: "Trần Quang Huy",
            authorAvatar: null,
            categoryName: "Game Development",
            avgRating: 4.8,
            countRating: 77,
            status: "ACCEPTED"
        },
        {
            id: 18,
            title: "Adobe Photoshop & Illustrator",
            subtitle: "Thiết kế đồ họa chuyên nghiệp",
            description: "Học Photoshop và Illustrator để thiết kế đồ họa chuyên nghiệp.",
            price: 299.99,
            duration: 40,
            language: "Tiếng Việt",
            level: "BEGINNER",
            thumbnail: "photoshop-thumbnail.jpg",
            previewVideo: "photoshop-preview.mp4",
            authorName: "Đỗ Thanh Trúc",
            authorAvatar: null,
            categoryName: "Design",
            avgRating: 4.5,
            countRating: 100,
            status: "ACCEPTED"
        },
        {
            id: 19,
            title: "Machine Learning với Python",
            subtitle: "Học máy từ cơ bản đến nâng cao",
            description: "Tìm hiểu về thuật toán Machine Learning và ứng dụng thực tế với Python.",
            price: 599.99,
            duration: 50,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "ml-python-thumbnail.jpg",
            previewVideo: "ml-python-preview.mp4",
            authorName: "Vũ Hoàng Nam",
            authorAvatar: null,
            categoryName: "Machine Learning",
            avgRating: 4.8,
            countRating: 95,
            status: "ACCEPTED"
        },
        {
            id: 20,
            title: "Deep Learning & AI",
            subtitle: "Trí tuệ nhân tạo chuyên sâu",
            description: "Hiểu về Deep Learning, mạng nơ-ron nhân tạo và ứng dụng AI.",
            price: 699.99,
            duration: 60,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "deep-learning-thumbnail.jpg",
            previewVideo: "deep-learning-preview.mp4",
            authorName: "Phạm Thanh Bình",
            authorAvatar: null,
            categoryName: "Artificial Intelligence",
            avgRating: 4.9,
            countRating: 80,
            status: "ACCEPTED"
        },
        {
            id: 21,
            title: "Kubernetes & Docker",
            subtitle: "Triển khai ứng dụng với Docker & Kubernetes",
            description: "Học cách sử dụng Docker và Kubernetes để triển khai ứng dụng hiện đại.",
            price: 499.99,
            duration: 45,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "docker-kubernetes-thumbnail.jpg",
            previewVideo: "docker-kubernetes-preview.mp4",
            authorName: "Nguyễn Văn Minh",
            authorAvatar: null,
            categoryName: "DevOps",
            avgRating: 4.7,
            countRating: 85,
            status: "ACCEPTED"
        },
        {
            id: 22,
            title: "DevOps & CI/CD Pipelines",
            subtitle: "Tích hợp & triển khai liên tục",
            description: "Hiểu về DevOps và cách xây dựng quy trình CI/CD hiệu quả.",
            price: 549.99,
            duration: 55,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "devops-thumbnail.jpg",
            previewVideo: "devops-preview.mp4",
            authorName: "Trần Văn Phúc",
            authorAvatar: null,
            categoryName: "DevOps",
            avgRating: 4.8,
            countRating: 78,
            status: "ACCEPTED"
        },
        {
            id: 23,
            title: "React Native & Mobile Development",
            subtitle: "Xây dựng ứng dụng di động đa nền tảng",
            description: "Lập trình ứng dụng di động với React Native cho iOS và Android.",
            price: 399.99,
            duration: 40,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "react-native-thumbnail.jpg",
            previewVideo: "react-native-preview.mp4",
            authorName: "Lê Minh Tuấn",
            authorAvatar: null,
            categoryName: "Mobile Development",
            avgRating: 4.7,
            countRating: 92,
            status: "ACCEPTED"
        },
        {
            id: 24,
            title: "Spring Boot Microservices",
            subtitle: "Xây dựng hệ thống Microservices với Spring Boot",
            description: "Khóa học chuyên sâu về phát triển hệ thống Microservices bằng Spring Boot.",
            price: 499.99,
            duration: 50,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "spring-microservices-thumbnail.jpg",
            previewVideo: "spring-microservices-preview.mp4",
            authorName: "Nguyễn Văn Hùng",
            authorAvatar: null,
            categoryName: "Spring Boot",
            avgRating: 4.8,
            countRating: 85,
            status: "ACCEPTED"
        },
        {
            id: 25,
            title: "Vue.js từ cơ bản đến nâng cao",
            subtitle: "Học Vue.js để phát triển ứng dụng hiện đại",
            description: "Tìm hiểu Vue.js, Vue Router, Vuex và cách xây dựng SPA.",
            price: 349.99,
            duration: 35,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "vuejs-thumbnail.jpg",
            previewVideo: "vuejs-preview.mp4",
            authorName: "Phạm Đình Khoa",
            authorAvatar: null,
            categoryName: "Vue.js",
            avgRating: 4.6,
            countRating: 88,
            status: "ACCEPTED"
        },
        {
            id: 26,
            title: "TypeScript cho lập trình viên",
            subtitle: "Nâng cấp kỹ năng JavaScript với TypeScript",
            description: "Học TypeScript từ cơ bản đến nâng cao để phát triển ứng dụng mạnh mẽ.",
            price: 299.99,
            duration: 30,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "typescript-thumbnail.jpg",
            previewVideo: "typescript-preview.mp4",
            authorName: "Ngô Minh Hiếu",
            authorAvatar: null,
            categoryName: "TypeScript",
            avgRating: 4.7,
            countRating: 80,
            status: "ACCEPTED"
        },
        {
            id: 27,
            title: "Next.js & SSR",
            subtitle: "Phát triển ứng dụng React với Next.js",
            description: "Học cách sử dụng Next.js để xây dựng ứng dụng web mạnh mẽ với Server-Side Rendering.",
            price: 399.99,
            duration: 40,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "nextjs-thumbnail.jpg",
            previewVideo: "nextjs-preview.mp4",
            authorName: "Bùi Văn Dũng",
            authorAvatar: null,
            categoryName: "Next.js",
            avgRating: 4.7,
            countRating: 75,
            status: "ACCEPTED"
        },
        {
            id: 28,
            title: "NestJS & Backend Development",
            subtitle: "Xây dựng backend mạnh mẽ với NestJS",
            description: "Tìm hiểu cách sử dụng NestJS để phát triển API hiệu suất cao.",
            price: 449.99,
            duration: 45,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "nestjs-thumbnail.jpg",
            previewVideo: "nestjs-preview.mp4",
            authorName: "Lý Minh Hoàng",
            authorAvatar: null,
            categoryName: "NestJS",
            avgRating: 4.8,
            countRating: 85,
            status: "ACCEPTED"
        },
        {
            id: 29,
            title: "Blockchain & Web3",
            subtitle: "Hiểu về Blockchain và các ứng dụng Web3",
            description: "Khóa học giúp bạn nắm vững công nghệ Blockchain, hợp đồng thông minh và Web3.",
            price: 699.99,
            duration: 55,
            language: "Tiếng Việt",
            level: "EXPERT",
            thumbnail: "blockchain-thumbnail.jpg",
            previewVideo: "blockchain-preview.mp4",
            authorName: "Đỗ Thanh Tùng",
            authorAvatar: null,
            categoryName: "Blockchain",
            avgRating: 4.8,
            countRating: 90,
            status: "ACCEPTED"
        },
        {
            id: 30,
            title: "Cybersecurity Fundamentals",
            subtitle: "Bảo mật hệ thống và dữ liệu",
            description: "Tìm hiểu về bảo mật mạng, mã hóa dữ liệu và cách phòng chống các cuộc tấn công.",
            price: 499.99,
            duration: 50,
            language: "Tiếng Việt",
            level: "INTERMEDIATE",
            thumbnail: "cybersecurity-thumbnail.jpg",
            previewVideo: "cybersecurity-preview.mp4",
            authorName: "Nguyễn Đăng Khoa",
            authorAvatar: null,
            categoryName: "Cybersecurity",
            avgRating: 4.7,
            countRating: 85,
            status: "ACCEPTED"
        },
        {
            id: 31,
            title: "UI/UX Design",
            subtitle: "Thiết kế trải nghiệm người dùng chuyên nghiệp",
            description: "Khóa học giúp bạn hiểu về UX/UI, Figma, wireframing và thiết kế giao diện chuyên nghiệp.",
            price: 399.99,
            duration: 40,
            language: "Tiếng Việt",
            level: "BEGINNER",
            thumbnail: "uiux-thumbnail.jpg",
            previewVideo: "uiux-preview.mp4",
            authorName: "Lê Thanh Hà",
            authorAvatar: null,
            categoryName: "Design",
            avgRating: 4.6,
            countRating: 88,
            status: "ACCEPTED"
        }
    ]
    vouchers = [
        {
            id: 1,
            code: "DISCOUNT10",
            description: "Giảm giá 10% cho đơn hàng",
            discountType: "PERCENTAGE",
            discountValue: 10.00,
            startDate: "2024-10-01T00:00:00",
            endDate: "2024-10-31T23:59:59",
            isActive: "INACTIVE"
        },
        {
            id: 2,
            code: "FREESHIP50",
            description: "Miễn phí vận chuyển cho đơn hàng từ 50K",
            discountType: "FIXED_AMOUNT",
            discountValue: 50.00,
            startDate: "2024-11-01T00:00:00",
            endDate: "2024-11-30T23:59:59",
            isActive: "ACTIVE"
        },
        {
            id: 3,
            code: "WELCOME20",
            description: "Giảm ngay 20K cho khách hàng mới",
            discountType: "FIXED_AMOUNT",
            discountValue: 20.00,
            startDate: "2024-09-15T00:00:00",
            endDate: "2024-12-15T23:59:59",
            isActive: "ACTIVE"
        },
        {
            id: 4,
            code: "BLACKFRIDAY30",
            description: "Giảm 30% cho tất cả đơn hàng dịp Black Friday",
            discountType: "PERCENTAGE",
            discountValue: 30.00,
            startDate: "2024-11-25T00:00:00",
            endDate: "2024-11-29T23:59:59",
            isActive: "INACTIVE"
        },
        {
            id: 5,
            code: "YEAR-END50",
            description: "Giảm 50K cho đơn hàng từ 500K",
            discountType: "FIXED_AMOUNT",
            discountValue: 50.00,
            startDate: "2024-12-01T00:00:00",
            endDate: "2025-12-31T23:59:59",
            isActive: "ACTIVE"
        }
    ]
    getAllVouchers(){
        return this.vouchers;
    }
    
    
    
      getAllCourses() {
        return this.courses;
      }
}